name: cpp-linter
on: [push]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      
      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@v2
        id:   linter
        continue-on-error: true
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sources: "src/**/*.cpp,src/**/*.h"
          style: file # Uses your project's .clang-format file
          files-changed-only: false
          thread-comments: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: apply clang-format fixes"
